//! Build script for Deoxys Core
//! Generates C header file using cbindgen for iOS FFI integration
//! Copyright (c) 2025 Axiom Hive. All rights reserved.

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();
    let output_file = PathBuf::from(&crate_dir)
        .join("include")
        .join(format!("{}.h", package_name));

    // Ensure include directory exists
    std::fs::create_dir_all(PathBuf::from(&crate_dir).join("include"))
        .expect("Failed to create include directory");

    // Configure cbindgen
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        header: Some(String::from(
            "/* Deoxys Core FFI - C API for iOS Integration */\n\
             /* Copyright (c) 2025 Axiom Hive. All rights reserved. */\n\
             /* \n\
              * This header provides a C-compatible interface to the Deoxys RIK engine.\n\
              * Safe to use from Swift, Objective-C, and C/C++.\n\
              */"
        )),
        include_guard: Some(String::from("DEOXYS_CORE_H")),
        autogen_warning: Some(String::from(
            "/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */"
        )),
        tab_width: 4,
        line_length: 100,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        style: cbindgen::Style::Both,
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(output_file);

    // Tell Cargo to rerun if FFI module changes
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=src/rik.rs");
    println!("cargo:rerun-if-changed=src/state.rs");
}
